name: Build README.md

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: fetching all commits
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.26.0
      - run: php generate.php
